package com.tmb.payment.wsdl.xpress.billpmtport;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-22T09:53:07.553+07:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "BillPmt", 
                  targetNamespace = "http://www.fnf.com/xes/BillPmtPort/") 
public class BillPmt extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("http://www.fnf.com/xes/BillPmtPort/", "BillPmt");
    public final static QName BillPmtPort = new QName("http://www.fnf.com/xes/BillPmtPort/", "BillPmtPort");

    public BillPmt(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BillPmt(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillPmt() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public BillPmt(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BillPmt(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BillPmt(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns BillPmtPortType
     */
    @WebEndpoint(name = "BillPmtPort")
    public BillPmtPortType getBillPmtPort() {
        return super.getPort(BillPmtPort, BillPmtPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BillPmtPortType
     */
    @WebEndpoint(name = "BillPmtPort")
    public BillPmtPortType getBillPmtPort(WebServiceFeature... features) {
        return super.getPort(BillPmtPort, BillPmtPortType.class, features);
    }

}
