package com.tmb.payment.wsdl.xpress.billpmtport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-02-22T09:53:07.345+07:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://www.fnf.com/xes/BillPmtPort/", name = "BillPmtPortType")
@XmlSeeAlso({com.tmb.payment.wsdl.xpress.vo.ObjectFactory.class, com.tmb.payment.wsdl.xpress.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface BillPmtPortType {

    @WebMethod(action = "urn:IFX")
    @WebResult(name = "BillPmtAddRs", targetNamespace = "http://www.fnf.com/xes", partName = "Rs")
    public com.tmb.payment.wsdl.xpress.BillPmtAddRsType add(
        @WebParam(partName = "Rq", name = "BillPmtAddRq", targetNamespace = "http://www.fnf.com/xes")
        com.tmb.payment.wsdl.xpress.BillPmtAddRqType rq
    );

    @WebMethod(action = "urn:IFX")
    @WebResult(name = "BillPmtInqRs", targetNamespace = "http://www.fnf.com/xes", partName = "Rs")
    public com.tmb.payment.wsdl.xpress.BillPmtInqRsType inq(
        @WebParam(partName = "Rq", name = "BillPmtInqRq", targetNamespace = "http://www.fnf.com/xes")
        com.tmb.payment.wsdl.xpress.BillPmtInqRqType rq
    );
}
