package com.tmb.payment.wsdl.ecm.wsimpl;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import com.tmb.payment.wsdl.ecm.wsapi.IDocumentService;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-05-02T17:27:11.839+07:00
 * Generated source version: 3.1.7
 * 
 */
@WebServiceClient(name = "DocumentServiceService"
				 , targetNamespace = "http://wsimpl.ds.ecm.clevel.com/") 
public class DocumentServiceService extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("http://wsimpl.ds.ecm.clevel.com/", "DocumentServiceService");
    public final static QName DocumentServicePort = new QName("http://wsimpl.ds.ecm.clevel.com/", "DocumentServicePort");

    public DocumentServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DocumentServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DocumentServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public DocumentServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DocumentServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DocumentServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns IDocumentService
     */
    @WebEndpoint(name = "DocumentServicePort")
    public IDocumentService getDocumentServicePort() {
        return super.getPort(DocumentServicePort, IDocumentService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IDocumentService
     */
    @WebEndpoint(name = "DocumentServicePort")
    public IDocumentService getDocumentServicePort(WebServiceFeature... features) {
        return super.getPort(DocumentServicePort, IDocumentService.class, features);
    }

}
