package com.tmb.payment.wsdl.ecm.wsapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.7
 * 2017-05-02T17:27:11.823+07:00
 * Generated source version: 3.1.7
 * 
 */
@WebService(targetNamespace = "http://wsapi.svc.ecm.clevel.com/", name = "IDocumentService")
@XmlSeeAlso({ObjectFactory.class})
public interface IDocumentService {

    @WebMethod
    @RequestWrapper(localName = "importDocuments", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ImportDocuments")
    @ResponseWrapper(localName = "importDocumentsResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ImportDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse importDocuments(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "deleteDocuments", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.DeleteDocuments")
    @ResponseWrapper(localName = "deleteDocumentsResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.DeleteDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse deleteDocuments(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "checkStatus", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.CheckStatus")
    @ResponseWrapper(localName = "checkStatusResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.CheckStatusResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse checkStatus(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "resubmitDocuments", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ResubmitDocuments")
    @ResponseWrapper(localName = "resubmitDocumentsResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ResubmitDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse resubmitDocuments(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "bulkUploadDocument", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.BulkUploadDocument")
    @ResponseWrapper(localName = "bulkUploadDocumentResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.BulkUploadDocumentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse bulkUploadDocument(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "viewDocument", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ViewDocument")
    @ResponseWrapper(localName = "viewDocumentResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ViewDocumentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse viewDocument(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "searchDocuments", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.SearchDocuments")
    @ResponseWrapper(localName = "searchDocumentsResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.SearchDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse searchDocuments(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "updateDocumentIndexes", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.UpdateDocumentIndexes")
    @ResponseWrapper(localName = "updateDocumentIndexesResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.UpdateDocumentIndexesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse updateDocumentIndexes(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );

    @WebMethod
    @RequestWrapper(localName = "exportDocuments", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ExportDocuments")
    @ResponseWrapper(localName = "exportDocumentsResponse", targetNamespace = "http://wsapi.svc.ecm.clevel.com/", className = "com.tmb.payment.wsdl.ecm.wsapi.ExportDocumentsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceResponse exportDocuments(
        @WebParam(name = "documentRequest", targetNamespace = "")
        com.tmb.payment.wsdl.ecm.wsapi.DocumentServiceRequest documentRequest
    );
}
