package com.tmb.payment.wsdl.ecmv2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-19T14:38:30.394+07:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "ACLService",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/")
public class ACLService extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "ACLService");
    public final static QName ACLServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "ACLServicePort");

    public ACLService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ACLService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACLService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ACLService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ACLService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ACLService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ACLServicePort
     */
    @WebEndpoint(name = "ACLServicePort")
    public ACLServicePort getACLServicePort() {
        return super.getPort(ACLServicePort, ACLServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ACLServicePort
     */
    @WebEndpoint(name = "ACLServicePort")
    public ACLServicePort getACLServicePort(WebServiceFeature... features) {
        return super.getPort(ACLServicePort, ACLServicePort.class, features);
    }

}
