package com.tmb.payment.wsdl.ecmv2;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-19T14:38:30.455+07:00
 * Generated source version: 3.2.6
 *
 */
@WebServiceClient(name = "ObjectService",
                  targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/")
public class ObjectService extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "ObjectService");
    public final static QName ObjectServicePort = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "ObjectServicePort");

    public ObjectService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ObjectService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ObjectService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ObjectService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ObjectService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ObjectService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ObjectServicePort
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectServicePort getObjectServicePort() {
        return super.getPort(ObjectServicePort, ObjectServicePort.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ObjectServicePort
     */
    @WebEndpoint(name = "ObjectServicePort")
    public ObjectServicePort getObjectServicePort(WebServiceFeature... features) {
        return super.getPort(ObjectServicePort, ObjectServicePort.class, features);
    }

}
