
package com.tmb.payment.wsdl.ecmv2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-19T14:38:29.826+07:00
 * Generated source version: 3.2.6
 *
 */
public final class PolicyServicePort_PolicyServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "PolicyService");

    private PolicyServicePort_PolicyServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = PolicyService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        PolicyService ss = new PolicyService(wsdlURL, SERVICE_NAME);
        PolicyServicePort port = ss.getPolicyServicePort();

        {
        System.out.println("Invoking removePolicy...");
        java.lang.String _removePolicy_repositoryId = "";
        java.lang.String _removePolicy_policyId = "";
        java.lang.String _removePolicy_objectId = "";
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _removePolicy_extensionVal = null;
        javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType> _removePolicy_extension = new javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType>(_removePolicy_extensionVal);
        try {
            port.removePolicy(_removePolicy_repositoryId, _removePolicy_policyId, _removePolicy_objectId, _removePolicy_extension);

            System.out.println("removePolicy._removePolicy_extension=" + _removePolicy_extension.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking applyPolicy...");
        java.lang.String _applyPolicy_repositoryId = "";
        java.lang.String _applyPolicy_policyId = "";
        java.lang.String _applyPolicy_objectId = "";
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _applyPolicy_extensionVal = null;
        javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType> _applyPolicy_extension = new javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType>(_applyPolicy_extensionVal);
        try {
            port.applyPolicy(_applyPolicy_repositoryId, _applyPolicy_policyId, _applyPolicy_objectId, _applyPolicy_extension);

            System.out.println("applyPolicy._applyPolicy_extension=" + _applyPolicy_extension.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAppliedPolicies...");
        java.lang.String _getAppliedPolicies_repositoryId = "";
        java.lang.String _getAppliedPolicies_objectId = "";
        java.lang.String _getAppliedPolicies_filter = "";
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _getAppliedPolicies_extension = null;
        try {
            java.util.List<com.tmb.payment.wsdl.ecmv2.CmisObjectType> _getAppliedPolicies__return = port.getAppliedPolicies(_getAppliedPolicies_repositoryId, _getAppliedPolicies_objectId, _getAppliedPolicies_filter, _getAppliedPolicies_extension);
            System.out.println("getAppliedPolicies.result=" + _getAppliedPolicies__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
