package com.tmb.payment.wsdl.ecmv2;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-19T14:38:30.194+07:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://docs.oasis-open.org/ns/cmis/ws/200908/", name = "RepositoryServicePort")
@XmlSeeAlso({ObjectFactory.class})
public interface RepositoryServicePort {

    @WebMethod(action = "getTypeChildren")
    @RequestWrapper(localName = "getTypeChildren", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeChildren")
    @ResponseWrapper(localName = "getTypeChildrenResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeChildrenResponse")
    @WebResult(name = "types", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
    public com.tmb.payment.wsdl.ecmv2.CmisTypeDefinitionListType getTypeChildren(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String typeId,
        @WebParam(name = "includePropertyDefinitions", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.Boolean includePropertyDefinitions,
        @WebParam(name = "maxItems", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.math.BigInteger maxItems,
        @WebParam(name = "skipCount", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.math.BigInteger skipCount,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "updateType")
    @RequestWrapper(localName = "updateType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.UpdateType")
    @ResponseWrapper(localName = "updateTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.UpdateTypeResponse")
    public void updateType(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        javax.xml.ws.Holder<CmisTypeDefinitionType> type,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "deleteType")
    @RequestWrapper(localName = "deleteType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.DeleteType")
    @ResponseWrapper(localName = "deleteTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.DeleteTypeResponse")
    public void deleteType(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String typeId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        javax.xml.ws.Holder<CmisExtensionType> extension
    ) throws CmisException;

    @WebMethod(action = "createType")
    @RequestWrapper(localName = "createType", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.CreateType")
    @ResponseWrapper(localName = "createTypeResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.CreateTypeResponse")
    public void createType(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(mode = WebParam.Mode.INOUT, name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        javax.xml.ws.Holder<CmisTypeDefinitionType> type,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "getTypeDescendants")
    @RequestWrapper(localName = "getTypeDescendants", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeDescendants")
    @ResponseWrapper(localName = "getTypeDescendantsResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeDescendantsResponse")
    @WebResult(name = "types", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
    public java.util.List<com.tmb.payment.wsdl.ecmv2.CmisTypeContainer> getTypeDescendants(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String typeId,
        @WebParam(name = "depth", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.math.BigInteger depth,
        @WebParam(name = "includePropertyDefinitions", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.Boolean includePropertyDefinitions,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "getRepositoryInfo")
    @RequestWrapper(localName = "getRepositoryInfo", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetRepositoryInfo")
    @ResponseWrapper(localName = "getRepositoryInfoResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetRepositoryInfoResponse")
    @WebResult(name = "repositoryInfo", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
    public com.tmb.payment.wsdl.ecmv2.CmisRepositoryInfoType getRepositoryInfo(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "getTypeDefinition")
    @RequestWrapper(localName = "getTypeDefinition", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeDefinition")
    @ResponseWrapper(localName = "getTypeDefinitionResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetTypeDefinitionResponse")
    @WebResult(name = "type", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
    public com.tmb.payment.wsdl.ecmv2.CmisTypeDefinitionType getTypeDefinition(
        @WebParam(name = "repositoryId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String repositoryId,
        @WebParam(name = "typeId", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        java.lang.String typeId,
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;

    @WebMethod(action = "getRepositories")
    @RequestWrapper(localName = "getRepositories", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetRepositories")
    @ResponseWrapper(localName = "getRepositoriesResponse", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/", className = "com.tmb.payment.wsdl.ecmv2.GetRepositoriesResponse")
    @WebResult(name = "repositories", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
    public java.util.List<com.tmb.payment.wsdl.ecmv2.CmisRepositoryEntryType> getRepositories(
        @WebParam(name = "extension", targetNamespace = "http://docs.oasis-open.org/ns/cmis/messaging/200908/")
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType extension
    ) throws CmisException;
}
