
package com.tmb.payment.wsdl.ecmv2;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-12-19T14:38:29.946+07:00
 * Generated source version: 3.2.6
 *
 */
public final class VersioningServicePort_VersioningServicePort_Client {

    private static final QName SERVICE_NAME = new QName("http://docs.oasis-open.org/ns/cmis/ws/200908/", "VersioningService");

    private VersioningServicePort_VersioningServicePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = VersioningService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        VersioningService ss = new VersioningService(wsdlURL, SERVICE_NAME);
        VersioningServicePort port = ss.getVersioningServicePort();

        {
        System.out.println("Invoking checkOut...");
        java.lang.String _checkOut_repositoryId = "";
        java.lang.String _checkOut_objectIdVal = "";
        javax.xml.ws.Holder<java.lang.String> _checkOut_objectId = new javax.xml.ws.Holder<java.lang.String>(_checkOut_objectIdVal);
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _checkOut_extensionVal = null;
        javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType> _checkOut_extension = new javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType>(_checkOut_extensionVal);
        javax.xml.ws.Holder<java.lang.Boolean> _checkOut_contentCopied = new javax.xml.ws.Holder<java.lang.Boolean>();
        try {
            port.checkOut(_checkOut_repositoryId, _checkOut_objectId, _checkOut_extension, _checkOut_contentCopied);

            System.out.println("checkOut._checkOut_objectId=" + _checkOut_objectId.value);
            System.out.println("checkOut._checkOut_extension=" + _checkOut_extension.value);
            System.out.println("checkOut._checkOut_contentCopied=" + _checkOut_contentCopied.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking cancelCheckOut...");
        java.lang.String _cancelCheckOut_repositoryId = "";
        java.lang.String _cancelCheckOut_objectId = "";
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _cancelCheckOut_extensionVal = null;
        javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType> _cancelCheckOut_extension = new javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType>(_cancelCheckOut_extensionVal);
        try {
            port.cancelCheckOut(_cancelCheckOut_repositoryId, _cancelCheckOut_objectId, _cancelCheckOut_extension);

            System.out.println("cancelCheckOut._cancelCheckOut_extension=" + _cancelCheckOut_extension.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getObjectOfLatestVersion...");
        java.lang.String _getObjectOfLatestVersion_repositoryId = "";
        java.lang.String _getObjectOfLatestVersion_objectId = "";
        java.lang.Boolean _getObjectOfLatestVersion_major = null;
        java.lang.String _getObjectOfLatestVersion_filter = "";
        java.lang.Boolean _getObjectOfLatestVersion_includeAllowableActions = null;
        com.tmb.payment.wsdl.ecmv2.EnumIncludeRelationships _getObjectOfLatestVersion_includeRelationships = null;
        java.lang.String _getObjectOfLatestVersion_renditionFilter = "";
        java.lang.Boolean _getObjectOfLatestVersion_includePolicyIds = null;
        java.lang.Boolean _getObjectOfLatestVersion_includeACL = null;
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _getObjectOfLatestVersion_extension = null;
        try {
            com.tmb.payment.wsdl.ecmv2.CmisObjectType _getObjectOfLatestVersion__return = port.getObjectOfLatestVersion(_getObjectOfLatestVersion_repositoryId, _getObjectOfLatestVersion_objectId, _getObjectOfLatestVersion_major, _getObjectOfLatestVersion_filter, _getObjectOfLatestVersion_includeAllowableActions, _getObjectOfLatestVersion_includeRelationships, _getObjectOfLatestVersion_renditionFilter, _getObjectOfLatestVersion_includePolicyIds, _getObjectOfLatestVersion_includeACL, _getObjectOfLatestVersion_extension);
            System.out.println("getObjectOfLatestVersion.result=" + _getObjectOfLatestVersion__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getAllVersions...");
        java.lang.String _getAllVersions_repositoryId = "";
        java.lang.String _getAllVersions_objectId = "";
        java.lang.String _getAllVersions_filter = "";
        java.lang.Boolean _getAllVersions_includeAllowableActions = null;
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _getAllVersions_extension = null;
        try {
            java.util.List<com.tmb.payment.wsdl.ecmv2.CmisObjectType> _getAllVersions__return = port.getAllVersions(_getAllVersions_repositoryId, _getAllVersions_objectId, _getAllVersions_filter, _getAllVersions_includeAllowableActions, _getAllVersions_extension);
            System.out.println("getAllVersions.result=" + _getAllVersions__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking getPropertiesOfLatestVersion...");
        java.lang.String _getPropertiesOfLatestVersion_repositoryId = "";
        java.lang.String _getPropertiesOfLatestVersion_objectId = "";
        java.lang.Boolean _getPropertiesOfLatestVersion_major = null;
        java.lang.String _getPropertiesOfLatestVersion_filter = "";
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _getPropertiesOfLatestVersion_extension = null;
        try {
            com.tmb.payment.wsdl.ecmv2.CmisPropertiesType _getPropertiesOfLatestVersion__return = port.getPropertiesOfLatestVersion(_getPropertiesOfLatestVersion_repositoryId, _getPropertiesOfLatestVersion_objectId, _getPropertiesOfLatestVersion_major, _getPropertiesOfLatestVersion_filter, _getPropertiesOfLatestVersion_extension);
            System.out.println("getPropertiesOfLatestVersion.result=" + _getPropertiesOfLatestVersion__return);

        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking checkIn...");
        java.lang.String _checkIn_repositoryId = "";
        java.lang.String _checkIn_objectIdVal = "";
        javax.xml.ws.Holder<java.lang.String> _checkIn_objectId = new javax.xml.ws.Holder<java.lang.String>(_checkIn_objectIdVal);
        java.lang.Boolean _checkIn_major = null;
        com.tmb.payment.wsdl.ecmv2.CmisPropertiesType _checkIn_properties = null;
        com.tmb.payment.wsdl.ecmv2.CmisContentStreamType _checkIn_contentStream = null;
        java.lang.String _checkIn_checkinComment = "";
        java.util.List<java.lang.String> _checkIn_policies = null;
        com.tmb.payment.wsdl.ecmv2.CmisAccessControlListType _checkIn_addACEs = null;
        com.tmb.payment.wsdl.ecmv2.CmisAccessControlListType _checkIn_removeACEs = null;
        com.tmb.payment.wsdl.ecmv2.CmisExtensionType _checkIn_extensionVal = null;
        javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType> _checkIn_extension = new javax.xml.ws.Holder<com.tmb.payment.wsdl.ecmv2.CmisExtensionType>(_checkIn_extensionVal);
        try {
            port.checkIn(_checkIn_repositoryId, _checkIn_objectId, _checkIn_major, _checkIn_properties, _checkIn_contentStream, _checkIn_checkinComment, _checkIn_policies, _checkIn_addACEs, _checkIn_removeACEs, _checkIn_extension);

            System.out.println("checkIn._checkIn_objectId=" + _checkIn_objectId.value);
            System.out.println("checkIn._checkIn_extension=" + _checkIn_extension.value);
        } catch (CmisException e) {
            System.out.println("Expected exception: cmisException has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
