package com.tmb.payment.wsdl.dbd;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.6
 * 2018-10-11T17:37:35.572+07:00
 * Generated source version: 3.2.6
 *
 */
@WebService(targetNamespace = "http://service.payment.dbd.gov/", name = "DbdPayment")
@XmlSeeAlso({ObjectFactory.class})
public interface DbdPayment {

    @WebMethod
    @Action(input = "http://service.payment.dbd.gov/DbdPayment/realTimePaymentRequest", output = "http://service.payment.dbd.gov/DbdPayment/realTimePaymentResponse")
    @RequestWrapper(localName = "realTimePayment", targetNamespace = "http://service.payment.dbd.gov/", className = "com.tmb.payment.wsdl.dbd.RealTimePayment")
    @ResponseWrapper(localName = "realTimePaymentResponse", targetNamespace = "http://service.payment.dbd.gov/", className = "com.tmb.payment.wsdl.dbd.RealTimePaymentResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String realTimePayment(
        @WebParam(name = "message", targetNamespace = "")
        com.tmb.payment.wsdl.dbd.PaymentPayLoad message
    );

    @WebMethod
    @Action(input = "http://service.payment.dbd.gov/DbdPayment/approveBeforePayRequest", output = "http://service.payment.dbd.gov/DbdPayment/approveBeforePayResponse")
    @RequestWrapper(localName = "approveBeforePay", targetNamespace = "http://service.payment.dbd.gov/", className = "com.tmb.payment.wsdl.dbd.ApproveBeforePay")
    @ResponseWrapper(localName = "approveBeforePayResponse", targetNamespace = "http://service.payment.dbd.gov/", className = "com.tmb.payment.wsdl.dbd.ApproveBeforePayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String approveBeforePay(
        @WebParam(name = "bankCode", targetNamespace = "")
        java.lang.String bankCode,
        @WebParam(name = "serviceCode", targetNamespace = "")
        java.lang.String serviceCode,
        @WebParam(name = "ref1", targetNamespace = "")
        java.lang.String ref1,
        @WebParam(name = "ref2", targetNamespace = "")
        java.lang.String ref2,
        @WebParam(name = "amount", targetNamespace = "")
        float amount
    );
}
